package com.contag.app.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT".
 */
public class Contact {

    private Long id;
    private String createdOn;
    private String updatedOn;
    private String contactName;
    private String contactNumber;
    private String invitedOn;
    private Boolean isOnContag;
    private Boolean isMuted;
    private Boolean isBlocked;
    private Boolean isInvited;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, String createdOn, String updatedOn, String contactName, String contactNumber, String invitedOn, Boolean isOnContag, Boolean isMuted, Boolean isBlocked, Boolean isInvited) {
        this.id = id;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.contactName = contactName;
        this.contactNumber = contactNumber;
        this.invitedOn = invitedOn;
        this.isOnContag = isOnContag;
        this.isMuted = isMuted;
        this.isBlocked = isBlocked;
        this.isInvited = isInvited;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(String createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(String updatedOn) {
        this.updatedOn = updatedOn;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    public String getInvitedOn() {
        return invitedOn;
    }

    public void setInvitedOn(String invitedOn) {
        this.invitedOn = invitedOn;
    }

    public Boolean getIsOnContag() {
        return isOnContag;
    }

    public void setIsOnContag(Boolean isOnContag) {
        this.isOnContag = isOnContag;
    }

    public Boolean getIsMuted() {
        return isMuted;
    }

    public void setIsMuted(Boolean isMuted) {
        this.isMuted = isMuted;
    }

    public Boolean getIsBlocked() {
        return isBlocked;
    }

    public void setIsBlocked(Boolean isBlocked) {
        this.isBlocked = isBlocked;
    }

    public Boolean getIsInvited() {
        return isInvited;
    }

    public void setIsInvited(Boolean isInvited) {
        this.isInvited = isInvited;
    }

}
