package com.contag.app.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.contag.app.model.Contact;
import com.contag.app.model.ContagContag;
import com.contag.app.model.Interest;
import com.contag.app.model.SocialProfile;

import com.contag.app.model.ContactDao;
import com.contag.app.model.ContagContagDao;
import com.contag.app.model.InterestDao;
import com.contag.app.model.SocialProfileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig contagContagDaoConfig;
    private final DaoConfig interestDaoConfig;
    private final DaoConfig socialProfileDaoConfig;

    private final ContactDao contactDao;
    private final ContagContagDao contagContagDao;
    private final InterestDao interestDao;
    private final SocialProfileDao socialProfileDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        contagContagDaoConfig = daoConfigMap.get(ContagContagDao.class).clone();
        contagContagDaoConfig.initIdentityScope(type);

        interestDaoConfig = daoConfigMap.get(InterestDao.class).clone();
        interestDaoConfig.initIdentityScope(type);

        socialProfileDaoConfig = daoConfigMap.get(SocialProfileDao.class).clone();
        socialProfileDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        contagContagDao = new ContagContagDao(contagContagDaoConfig, this);
        interestDao = new InterestDao(interestDaoConfig, this);
        socialProfileDao = new SocialProfileDao(socialProfileDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(ContagContag.class, contagContagDao);
        registerDao(Interest.class, interestDao);
        registerDao(SocialProfile.class, socialProfileDao);
    }
    
    public void clear() {
        contactDaoConfig.getIdentityScope().clear();
        contagContagDaoConfig.getIdentityScope().clear();
        interestDaoConfig.getIdentityScope().clear();
        socialProfileDaoConfig.getIdentityScope().clear();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ContagContagDao getContagContagDao() {
        return contagContagDao;
    }

    public InterestDao getInterestDao() {
        return interestDao;
    }

    public SocialProfileDao getSocialProfileDao() {
        return socialProfileDao;
    }

}
