package com.contag.app.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SOCIAL_PLATFORM".
 */
public class SocialPlatform {

    private Long id;
    private String platformName;
    private String platformBaseUrl;

    public SocialPlatform() {
    }

    public SocialPlatform(Long id) {
        this.id = id;
    }

    public SocialPlatform(Long id, String platformName, String platformBaseUrl) {
        this.id = id;
        this.platformName = platformName;
        this.platformBaseUrl = platformBaseUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPlatformName() {
        return platformName;
    }

    public void setPlatformName(String platformName) {
        this.platformName = platformName;
    }

    public String getPlatformBaseUrl() {
        return platformBaseUrl;
    }

    public void setPlatformBaseUrl(String platformBaseUrl) {
        this.platformBaseUrl = platformBaseUrl;
    }

}
