package com.contag.app.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.contag.app.model.SocialPlatform;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SOCIAL_PLATFORM".
*/
public class SocialPlatformDao extends AbstractDao<SocialPlatform, Long> {

    public static final String TABLENAME = "SOCIAL_PLATFORM";

    /**
     * Properties of entity SocialPlatform.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PlatformName = new Property(1, String.class, "platformName", false, "PLATFORM_NAME");
        public final static Property PlatformBaseUrl = new Property(2, String.class, "platformBaseUrl", false, "PLATFORM_BASE_URL");
    };


    public SocialPlatformDao(DaoConfig config) {
        super(config);
    }
    
    public SocialPlatformDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SOCIAL_PLATFORM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PLATFORM_NAME\" TEXT," + // 1: platformName
                "\"PLATFORM_BASE_URL\" TEXT);"); // 2: platformBaseUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SOCIAL_PLATFORM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SocialPlatform entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String platformName = entity.getPlatformName();
        if (platformName != null) {
            stmt.bindString(2, platformName);
        }
 
        String platformBaseUrl = entity.getPlatformBaseUrl();
        if (platformBaseUrl != null) {
            stmt.bindString(3, platformBaseUrl);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SocialPlatform readEntity(Cursor cursor, int offset) {
        SocialPlatform entity = new SocialPlatform( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // platformName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // platformBaseUrl
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SocialPlatform entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPlatformName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPlatformBaseUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SocialPlatform entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SocialPlatform entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
